apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
spec:
  containers:
    - name: curl
      image: appropriate/curl
      command: ["/bin/sh"]
      args: ["-c","while true; do echo hello; sleep 10;done"]
      resources:
        limits:
          cpu: 0.1
          memory: "10Mi"
