apiVersion: v1
kind: Pod
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  containers:
    - name: monolith
      image: kelseyhightower/monolith:1.0.0
      args:
        - "-http=0.0.0.0:8080"
        - "-health=0.0.0.0:8081"
        - "-secret=secret"
      ports:
        - name: http
          containerPort: 8080
        - name: health
          containerPort: 8081
