kind: Service
apiVersion: v1
metadata:
  name: "frontend"
spec:
  selector:
    app: "frontend"
  ports:
    - name: 443-tcp
      protocol: "TCP"
      port: 443
      targetPort: 8443

